int init_semaphores(sem_t **); 
int compare_ip(char *, u_char *); 
int send_dns();
void print_usage();
int init_packet_buffer(struct queue *);
int free_packet_buffer(char **); 
int dns_sender(char *, sem_t **, int, char *);
void print_buf(u_char *);
int dns_listener(char *, char *, sem_t **, int);
void build_dns(u_char *, u_char *);
struct udp_header *get_udp_ptr(u_char *); 
